FROM node:22-alpine AS builder

WORKDIR /app

COPY . .

RUN npm ci
RUN npm run build

FROM node:22-alpine

WORKDIR /app

COPY . .
RUN npm ci --omit=dev

COPY --from=builder /app/packages ./packages
COPY --from=builder /app/steam-bot/dist ./steam-bot/dist

WORKDIR /app/steam-bot

CMD ["npm", "start"]